global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ecommerce-api
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5004']

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
